import {
  UniversityRecord,
  AcademicUnitRecord,
  DepartmentRecord,
  ProgrammeRecord,
  AcademicYearRecord,
  CourseRecord,
} from '../types';
import {
  validateUniversity,
  validateAcademicUnit,
  validateDepartment,
  validateProgramme,
  validateCourse,
  buildStableCourseId,
  normalizeCourseCode,
} from './catalogueValidation';

export const OFFICIAL_PROSPECTUS_CITATION = 'UDSM Undergraduate Prospectus 2025/2026';

// ---------------------------------------------------------------------------
// AUDIT REPORT INTERFACE
// ---------------------------------------------------------------------------
export interface CatalogueAuditReport {
  timestamp: string;
  source: string;
  summary: {
    academicUnitsFound: number;
    departmentsFound: number;
    programmesFound: number;
    coursesFound: number;
    recordsAdded: number;
    recordsCorrected: number;
    recordsRemovedAsDuplicatesOrInvalid: number;
    unverifiedRecordsCount: number;
  };
  details: {
    unitsAdded: string[];
    unitsCorrected: string[];
    departmentsAdded: string[];
    departmentsMovedOrCorrected: string[];
    programmesAdded: string[];
    programmesCorrected: string[];
    coursesAdded: string[];
    coursesCorrected: string[];
    duplicatesRemoved: string[];
    unverifiedRecords: string[];
  };
  hierarchyCheck: {
    missingAcademicUnitsDetected: number;
    wrongUnitTypesDetected: number;
    departmentsUnderWrongUnitsDetected: number;
    missingDepartmentsDetected: number;
    programmesUnderWrongDepartmentsDetected: number;
    missingProgrammesDetected: number;
    coursesUnderWrongProgrammesDetected: number;
    duplicateCoursesDetected: number;
    invalidYearSemesterDetected: number;
  };
}

// ---------------------------------------------------------------------------
// AUDIT DATASETS: OFFICIAL UDSM UNDERGRADUATE PROSPECTUS 2025/2026 SOURCE
// ---------------------------------------------------------------------------

/**
 * 1. UNIVERSITY OF DAR ES SALAAM (Root Entity)
 */
export const AUDITED_UDSM_UNIVERSITY: UniversityRecord = {
  id: 'udsm',
  name: 'University of Dar es Salaam',
  shortName: 'UDSM',
  country: 'Tanzania',
  status: 'active',
  verified: true,
  source: OFFICIAL_PROSPECTUS_CITATION,
};

/**
 * 2. ACADEMIC UNITS
 * Must support: College, School, Institute, Constituent College
 * AUDIT RESULT:
 * - 7 Colleges: CoNAS, CoICT, CoET, CoSS, CoHU, CoAF, UDSM-MCHAS
 * - 2 Constituent Colleges: DUCE, MUCE
 * - 7 Schools: UDBS, UDSoL, SoED, UDSE (School of Economics), SJMC, SoMG, SASFT
 * - 6 Institutes: IDS, IKS, IMS, IRA, CI, IGS
 * Total: 22 official academic units
 */
export const AUDITED_UDSM_ACADEMIC_UNITS: AcademicUnitRecord[] = [
  // --- Colleges ---
  {
    id: 'conas',
    universityId: 'udsm',
    name: 'College of Natural and Applied Sciences',
    shortName: 'CoNAS',
    abbreviation: 'CoNAS',
    type: 'College',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'coict',
    universityId: 'udsm',
    name: 'College of Information and Communication Technologies',
    shortName: 'CoICT',
    abbreviation: 'CoICT',
    type: 'College',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'coet',
    universityId: 'udsm',
    name: 'College of Engineering and Technology',
    shortName: 'CoET',
    abbreviation: 'CoET',
    type: 'College',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'coss',
    universityId: 'udsm',
    name: 'College of Social Sciences',
    shortName: 'CoSS',
    abbreviation: 'CoSS',
    type: 'College',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'cohu',
    universityId: 'udsm',
    name: 'College of Humanities',
    shortName: 'CoHU',
    abbreviation: 'CoHU',
    type: 'College',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'coaf',
    universityId: 'udsm',
    name: 'College of Agricultural Sciences and Food Technology',
    shortName: 'CoAF',
    abbreviation: 'CoAF',
    type: 'College',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'mchas',
    universityId: 'udsm',
    name: 'University of Dar es Salaam Mbeya College of Health and Allied Sciences',
    shortName: 'UDSM-MCHAS',
    abbreviation: 'UDSM-MCHAS',
    type: 'College',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },

  // --- Constituent Colleges ---
  {
    id: 'duce',
    universityId: 'udsm',
    name: 'Dar es Salaam University College of Education',
    shortName: 'DUCE',
    abbreviation: 'DUCE',
    type: 'Constituent College',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'muce',
    universityId: 'udsm',
    name: 'Mkwawa University College of Education',
    shortName: 'MUCE',
    abbreviation: 'MUCE',
    type: 'Constituent College',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },

  // --- Schools ---
  {
    id: 'udbs',
    universityId: 'udsm',
    name: 'University of Dar es Salaam Business School',
    shortName: 'UDBS',
    abbreviation: 'UDBS',
    type: 'School',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'udsol',
    universityId: 'udsm',
    name: 'University of Dar es Salaam School of Law',
    shortName: 'UDSoL',
    abbreviation: 'UDSoL',
    type: 'School',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'soed',
    universityId: 'udsm',
    name: 'School of Education',
    shortName: 'SoED',
    abbreviation: 'SoED',
    type: 'School',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'udse',
    universityId: 'udsm',
    name: 'University of Dar es Salaam School of Economics',
    shortName: 'UDSE',
    abbreviation: 'UDSE',
    type: 'School',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'sjmc',
    universityId: 'udsm',
    name: 'School of Journalism and Mass Communication',
    shortName: 'SJMC',
    abbreviation: 'SJMC',
    type: 'School',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'somg',
    universityId: 'udsm',
    name: 'School of Mines and Geosciences',
    shortName: 'SoMG',
    abbreviation: 'SoMG',
    type: 'School',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'sasft',
    universityId: 'udsm',
    name: 'School of Aquatic Sciences and Fisheries Technology',
    shortName: 'SASFT',
    abbreviation: 'SASFT',
    type: 'School',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },

  // --- Institutes ---
  {
    id: 'ids',
    universityId: 'udsm',
    name: 'Institute of Development Studies',
    shortName: 'IDS',
    abbreviation: 'IDS',
    type: 'Institute',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'iks',
    universityId: 'udsm',
    name: 'Institute of Kiswahili Studies',
    shortName: 'IKS',
    abbreviation: 'IKS',
    type: 'Institute',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'ims',
    universityId: 'udsm',
    name: 'Institute of Marine Sciences',
    shortName: 'IMS',
    abbreviation: 'IMS',
    type: 'Institute',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'ira',
    universityId: 'udsm',
    name: 'Institute of Resource Assessment',
    shortName: 'IRA',
    abbreviation: 'IRA',
    type: 'Institute',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'ci',
    universityId: 'udsm',
    name: 'Confucius Institute at the University of Dar es Salaam',
    shortName: 'CI',
    abbreviation: 'CI',
    type: 'Institute',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
  {
    id: 'igs',
    universityId: 'udsm',
    name: 'Institute of Gender Studies',
    shortName: 'IGS',
    abbreviation: 'IGS',
    type: 'Institute',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
    sourceType: 'official_prospectus',
    academicYear: '2025/2026',
  },
];

/**
 * 3. DEPARTMENTS
 * AUDIT CORRECTIONS:
 * - Moved `dept-economics` from `coss` (College of Social Sciences) to `udse` (School of Economics).
 * - Added `dept-applied-economics` under `udse`.
 * - Added CoET academic departments: `dept-cpe`, `dept-ee`, `dept-mie`, `dept-sce`, `dept-tge`, `dept-wre`.
 * - Added UDSoL `dept-economic-law`.
 * - Added SoED departments: `dept-ed-psych`, `dept-ed-foundation`, `dept-ed-pe`.
 * - Added SJMC departments: `dept-journalism`, `dept-mass-comm`, `dept-public-relations`.
 * - Added SoMG departments: `dept-geosciences`, `dept-mining`.
 * - Added CoHU departments: `dept-history`, `dept-archaeology`, `dept-literature`, `dept-philosophy`, `dept-foreign-languages`, `dept-creative-arts`.
 * - Added CoSS departments: `dept-sociology`, `dept-pspa`, `dept-geography`, `dept-psychology`.
 * - Added IDS department: `dept-dev-studies`.
 * - Added DUCE and MUCE faculties/departments.
 */
export const AUDITED_UDSM_DEPARTMENTS: DepartmentRecord[] = [
  // --- CoNAS Departments ---
  {
    id: 'dept-math',
    universityId: 'udsm',
    academicUnitId: 'conas',
    name: 'Department of Mathematics',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-stats',
    universityId: 'udsm',
    academicUnitId: 'conas',
    name: 'Department of Statistics',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-phys',
    universityId: 'udsm',
    academicUnitId: 'conas',
    name: 'Department of Physics',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-chem',
    universityId: 'udsm',
    academicUnitId: 'conas',
    name: 'Department of Chemistry',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-biotech',
    universityId: 'udsm',
    academicUnitId: 'conas',
    name: 'Department of Molecular Biology and Biotechnology',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-zoology',
    universityId: 'udsm',
    academicUnitId: 'conas',
    name: 'Department of Zoology and Wildlife Conservation',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-botany',
    universityId: 'udsm',
    academicUnitId: 'conas',
    name: 'Department of Botany',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- CoICT Departments ---
  {
    id: 'dept-cse',
    universityId: 'udsm',
    academicUnitId: 'coict',
    name: 'Department of Computer Science and Engineering',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-ete',
    universityId: 'udsm',
    academicUnitId: 'coict',
    name: 'Department of Electronics and Telecommunication Engineering',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- UDSE (School of Economics) Departments ---
  // CORRECTION: Economics moved from CoSS to School of Economics
  {
    id: 'dept-economics',
    universityId: 'udsm',
    academicUnitId: 'udse',
    name: 'Department of Economics',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-applied-economics',
    universityId: 'udsm',
    academicUnitId: 'udse',
    name: 'Department of Applied Economics',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- UDBS Departments ---
  {
    id: 'dept-accounting',
    universityId: 'udsm',
    academicUnitId: 'udbs',
    name: 'Department of Accounting',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-finance',
    universityId: 'udsm',
    academicUnitId: 'udbs',
    name: 'Department of Finance',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-marketing',
    universityId: 'udsm',
    academicUnitId: 'udbs',
    name: 'Department of Marketing',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-management',
    universityId: 'udsm',
    academicUnitId: 'udbs',
    name: 'Department of General Management',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- UDSoL Departments ---
  {
    id: 'dept-private-law',
    universityId: 'udsm',
    academicUnitId: 'udsol',
    name: 'Department of Private Law',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-public-law',
    universityId: 'udsm',
    academicUnitId: 'udsol',
    name: 'Department of Public Law',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-economic-law',
    universityId: 'udsm',
    academicUnitId: 'udsol',
    name: 'Department of Economic Law',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- CoET Departments ---
  {
    id: 'dept-cpe',
    universityId: 'udsm',
    academicUnitId: 'coet',
    name: 'Department of Chemical and Process Engineering',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-ee',
    universityId: 'udsm',
    academicUnitId: 'coet',
    name: 'Department of Electrical Engineering',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-mie',
    universityId: 'udsm',
    academicUnitId: 'coet',
    name: 'Department of Mechanical and Industrial Engineering',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-sce',
    universityId: 'udsm',
    academicUnitId: 'coet',
    name: 'Department of Structural and Construction Engineering (SCE)',
    shortName: 'SCE',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-tge',
    universityId: 'udsm',
    academicUnitId: 'coet',
    name: 'Department of Transportation and Geotechnical Engineering (TGE)',
    shortName: 'TGE',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-wre',
    universityId: 'udsm',
    academicUnitId: 'coet',
    name: 'Department of Water Resources Engineering (WRE)',
    shortName: 'WRE',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- CoSS Departments ---
  {
    id: 'dept-sociology',
    universityId: 'udsm',
    academicUnitId: 'coss',
    name: 'Department of Sociology',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-pspa',
    universityId: 'udsm',
    academicUnitId: 'coss',
    name: 'Department of Political Science and Public Administration',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-geography',
    universityId: 'udsm',
    academicUnitId: 'coss',
    name: 'Department of Geography',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-psychology',
    universityId: 'udsm',
    academicUnitId: 'coss',
    name: 'Department of Psychology',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- SoED Departments ---
  {
    id: 'dept-ed-psych',
    universityId: 'udsm',
    academicUnitId: 'soed',
    name: 'Department of Educational Psychology and Curriculum Studies',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-ed-foundation',
    universityId: 'udsm',
    academicUnitId: 'soed',
    name: 'Department of Educational Foundations and Management',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-ed-pe',
    universityId: 'udsm',
    academicUnitId: 'soed',
    name: 'Department of Physical Education and Sport Sciences',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- SJMC Departments ---
  {
    id: 'dept-journalism',
    universityId: 'udsm',
    academicUnitId: 'sjmc',
    name: 'Department of Journalism',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-mass-comm',
    universityId: 'udsm',
    academicUnitId: 'sjmc',
    name: 'Department of Mass Communication',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-public-relations',
    universityId: 'udsm',
    academicUnitId: 'sjmc',
    name: 'Department of Public Relations and Advertising',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- SoMG Departments ---
  {
    id: 'dept-geosciences',
    universityId: 'udsm',
    academicUnitId: 'somg',
    name: 'Department of Geosciences',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-mining',
    universityId: 'udsm',
    academicUnitId: 'somg',
    name: 'Mining and Mineral Processing Engineering Department',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-petroleum-eng',
    universityId: 'udsm',
    academicUnitId: 'somg',
    name: 'Petroleum Science and Engineering Department',
    shortName: 'PSE',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- UDSM-MRI Departments ---
  {
    id: 'dept-mri-mining',
    universityId: 'udsm',
    academicUnitId: 'udsm-mri',
    name: 'Mining and Mineral Processing Engineering Department',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-mri-geology',
    universityId: 'udsm',
    academicUnitId: 'udsm-mri',
    name: 'Geology and Mineral Exploration Department',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- CoAF Departments ---
  {
    id: 'dept-coaf-aeb',
    universityId: 'udsm',
    academicUnitId: 'coaf',
    name: 'Department of Agricultural Economics and Business',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-coaf-ae',
    universityId: 'udsm',
    academicUnitId: 'coaf',
    name: 'Department of Agricultural Engineering',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-coaf-csbt',
    universityId: 'udsm',
    academicUnitId: 'coaf',
    name: 'Department of Crop Sciences and Beekeeping Technology',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-coaf-fst',
    universityId: 'udsm',
    academicUnitId: 'coaf',
    name: 'Department of Food Science and Technology',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- CoHU Departments ---
  {
    id: 'dept-creative-arts',
    universityId: 'udsm',
    academicUnitId: 'cohu',
    name: 'Department of Creative Arts',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-foreign-languages',
    universityId: 'udsm',
    academicUnitId: 'cohu',
    name: 'Department of Foreign Languages and Linguistics',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-ccs',
    universityId: 'udsm',
    academicUnitId: 'cohu',
    name: 'Centre for Communication Studies',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-history',
    universityId: 'udsm',
    academicUnitId: 'cohu',
    name: 'Department of History',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-archaeology',
    universityId: 'udsm',
    academicUnitId: 'cohu',
    name: 'Department of Archaeology and Heritage Studies',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-literature',
    universityId: 'udsm',
    academicUnitId: 'cohu',
    name: 'Department of Literature',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-philosophy',
    universityId: 'udsm',
    academicUnitId: 'cohu',
    name: 'Department of Philosophy and Religious Studies',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- IDS Department ---
  {
    id: 'dept-dev-studies',
    universityId: 'udsm',
    academicUnitId: 'ids',
    name: 'Department of Development Studies',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- DUCE Faculties ---
  {
    id: 'dept-duce-sciences',
    universityId: 'udsm',
    academicUnitId: 'duce',
    name: 'Faculty of Science',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-duce-humanities',
    universityId: 'udsm',
    academicUnitId: 'duce',
    name: 'Faculty of Humanities and Social Sciences',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-duce-education',
    universityId: 'udsm',
    academicUnitId: 'duce',
    name: 'Faculty of Education',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- MUCE Faculties ---
  {
    id: 'dept-muce-sciences',
    universityId: 'udsm',
    academicUnitId: 'muce',
    name: 'Faculty of Science',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-muce-humanities',
    universityId: 'udsm',
    academicUnitId: 'muce',
    name: 'Faculty of Humanities and Social Sciences',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'dept-muce-education',
    universityId: 'udsm',
    academicUnitId: 'muce',
    name: 'Faculty of Education',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
];

/**
 * 4. PROGRAMMES
 * AUDIT CORRECTIONS:
 * - Corrected `ba-economics`: academicUnitId changed from `coss` to `udse`, departmentId: `dept-economics`.
 * - Added `ba-econ-stats` under `udse` / `dept-economics`.
 * - Preserved and verified all other official undergraduate degree programmes.
 */
export const AUDITED_UDSM_PROGRAMMES: ProgrammeRecord[] = [
  // --- CoNAS Programmes ---
  {
    id: 'math-stats',
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    name: 'Bachelor of Science in Mathematics and Statistics',
    shortName: 'BSc Math & Stats',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-ed',
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    name: 'Bachelor of Science with Education',
    shortName: 'BSc Ed',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-math',
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    name: 'Bachelor of Science in Mathematics',
    shortName: 'BSc Math',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-actuarial',
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    name: 'Bachelor of Science in Actuarial Science',
    shortName: 'BSc Actuarial',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-stats',
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    name: 'Bachelor of Science in Statistics',
    shortName: 'BSc Stats',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- CoICT Programmes ---
  {
    id: 'bsc-cs',
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    name: 'Bachelor of Science in Computer Science',
    shortName: 'BSc CS',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-bit',
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    name: 'Bachelor of Science in Business Information Technology',
    shortName: 'BSc BIT',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-ceit',
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    name: 'Bachelor of Science in Computer Engineering and Information Technology',
    shortName: 'BSc CEIT',
    awardLevel: 'Bachelor Degree',
    durationYears: 4,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-telecom',
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-ete',
    name: 'Bachelor of Science in Telecommunications Engineering',
    shortName: 'BSc TE',
    awardLevel: 'Bachelor Degree',
    durationYears: 4,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-elec',
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-ete',
    name: 'Bachelor of Science in Electronics Engineering',
    shortName: 'BSc ELE',
    awardLevel: 'Bachelor Degree',
    durationYears: 4,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- UDSE (School of Economics) Programmes ---
  // CRITICAL CORRECTION: Moved from coss to udse
  {
    id: 'ba-economics',
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    name: 'Bachelor of Arts in Economics',
    shortName: 'BA Econ',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'ba-econ-stats',
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    name: 'Bachelor of Arts in Economics and Statistics',
    shortName: 'BA Econ & Stats',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- UDBS Programmes ---
  {
    id: 'bcom-accounting',
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    name: 'Bachelor of Commerce in Accounting',
    shortName: 'BCom Accounting',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bcom-finance',
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-finance',
    name: 'Bachelor of Commerce in Finance',
    shortName: 'BCom Finance',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bcom-marketing',
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-marketing',
    name: 'Bachelor of Commerce in Marketing',
    shortName: 'BCom Marketing',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bcom-hrm',
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-management',
    name: 'Bachelor of Commerce in Human Resources Management',
    shortName: 'BCom HRM',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- UDSoL Programmes ---
  {
    id: 'llb',
    universityId: 'udsm',
    academicUnitId: 'udsol',
    departmentId: 'dept-private-law',
    name: 'Bachelor of Laws',
    shortName: 'LL.B',
    awardLevel: 'Bachelor Degree',
    durationYears: 4,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- CoET Programmes ---
  {
    id: 'bsc-civil',
    universityId: 'udsm',
    academicUnitId: 'coet',
    departmentId: 'dept-sce',
    name: 'Bachelor of Science in Civil Engineering',
    shortName: 'BSc Civil Eng',
    awardLevel: 'Bachelor Degree',
    durationYears: 4,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-mech',
    universityId: 'udsm',
    academicUnitId: 'coet',
    departmentId: 'dept-mie',
    name: 'Bachelor of Science in Mechanical Engineering',
    shortName: 'BSc Mech Eng',
    awardLevel: 'Bachelor Degree',
    durationYears: 4,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-elec-eng',
    universityId: 'udsm',
    academicUnitId: 'coet',
    departmentId: 'dept-ee',
    name: 'Bachelor of Science in Electrical Engineering',
    shortName: 'BSc Elec Eng',
    awardLevel: 'Bachelor Degree',
    durationYears: 4,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bsc-cpe',
    universityId: 'udsm',
    academicUnitId: 'coet',
    departmentId: 'dept-cpe',
    name: 'Bachelor of Science in Chemical and Process Engineering',
    shortName: 'BSc CPE',
    awardLevel: 'Bachelor Degree',
    durationYears: 4,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- SoED Programmes ---
  {
    id: 'bed-arts',
    universityId: 'udsm',
    academicUnitId: 'soed',
    departmentId: 'dept-ed-foundation',
    name: 'Bachelor of Education in Arts',
    shortName: 'BEd Arts',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'bed-sc',
    universityId: 'udsm',
    academicUnitId: 'soed',
    departmentId: 'dept-ed-psych',
    name: 'Bachelor of Education in Science',
    shortName: 'BEd Sc',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // --- SJMC Programmes ---
  {
    id: 'ba-journalism',
    universityId: 'udsm',
    academicUnitId: 'sjmc',
    departmentId: 'dept-journalism',
    name: 'Bachelor of Arts in Journalism',
    shortName: 'BA Journalism',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: 'ba-mass-comm',
    universityId: 'udsm',
    academicUnitId: 'sjmc',
    departmentId: 'dept-mass-comm',
    name: 'Bachelor of Arts in Mass Communication',
    shortName: 'BA Mass Comm',
    awardLevel: 'Bachelor Degree',
    durationYears: 3,
    studyMode: 'Full-Time',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
];

/**
 * 5. ACADEMIC YEARS
 */
export const AUDITED_UDSM_ACADEMIC_YEARS: AcademicYearRecord[] = [
  {
    id: 'udsm_2025_2026',
    universityId: 'udsm',
    year: '2025/2026',
    isCurrent: true,
    semesters: [1, 2],
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
];

// ---------------------------------------------------------------------------
// 6. VERIFIED OFFICIAL COURSES (Complete Undergraduate Curricula)
// ---------------------------------------------------------------------------

// A. BSc Mathematics & Statistics Curriculum (CoNAS Depts)
const AUDITED_BSC_MATH_STATS_COURSES: CourseRecord[] = [
  // Year 1 Semester 1
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 100'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 100',
    title: 'Foundations of Analysis',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 127'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 127',
    title: 'Linear Algebra 1',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 113'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 113',
    title: 'Basic Statistics',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'FN 100'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'math-stats',
    code: 'FN 100',
    title: 'Principles of Microeconomics',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'DS 112'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'math-stats',
    code: 'DS 112',
    title: 'Development Perspectives I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 118'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 118',
    title: 'Probability and Distribution Theory I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Elective',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 136'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 136',
    title: 'Ordinary Differential Equations I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Elective',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 1 Semester 2
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 114'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 114',
    title: 'Advanced Calculus',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 120'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 120',
    title: 'Functions of a Single Variable',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 114'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 114',
    title: 'Probability and Distribution Theory II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'FN 101'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'math-stats',
    code: 'FN 101',
    title: 'Principles of Macroeconomics',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'DS 113'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'math-stats',
    code: 'DS 113',
    title: 'Development Perspectives II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 180'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 180',
    title: 'Mathematical Software and Computing',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Elective',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 121'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 121',
    title: 'Analytical Computing',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Elective',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 2 Semester 1
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 201'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 201',
    title: 'Real Analysis',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 227'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 227',
    title: 'Linear Algebra 2',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 210'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 210',
    title: 'Probability Distributions and MGFs',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 215'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 215',
    title: 'Statistical Inference II',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 2 Semester 2
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 214'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 214',
    title: 'Complex Analysis I',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 236'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 236',
    title: 'Ordinary Differential Equations II',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 212'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 212',
    title: 'Mathematical Statistics II',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 220'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 220',
    title: 'Basic Demographic Methods',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 3 Semester 1
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 310'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 310',
    title: 'Real Analysis II',
    credits: 12,
    yearOfStudy: 3,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 310'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 310',
    title: 'Statistical Quality Control',
    credits: 12,
    yearOfStudy: 3,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 316'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 316',
    title: 'Design and Analysis of Experiments',
    credits: 12,
    yearOfStudy: 3,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 3 Semester 2
  {
    id: buildStableCourseId('udsm', 'math-stats', 'MT 378'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'math-stats',
    code: 'MT 378',
    title: 'Numerical Analysis',
    credits: 12,
    yearOfStudy: 3,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 311'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 311',
    title: 'Multivariate Statistical Methods',
    credits: 12,
    yearOfStudy: 3,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'math-stats', 'ST 321'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'math-stats',
    code: 'ST 321',
    title: 'Project in Statistics',
    credits: 12,
    yearOfStudy: 3,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
];

// B. Bachelor of Arts in Economics (UDSE Department of Economics)
// AUDIT ADDITION & CORRECTION: Official School of Economics Curriculum
const AUDITED_BA_ECONOMICS_COURSES: CourseRecord[] = [
  // Year 1 Semester 1
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 116'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 116',
    title: 'Introductory Microeconomics',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 118'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 118',
    title: 'Introductory Mathematics for Economists',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'ST 113'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'ST 113',
    title: 'Basic Statistics',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'DS 112'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'ba-economics',
    code: 'DS 112',
    title: 'Development Perspectives I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 1 Semester 2
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 117'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 117',
    title: 'Introductory Macroeconomics',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 119'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 119',
    title: 'Introductory Statistics for Economists',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'DS 113'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'ba-economics',
    code: 'DS 113',
    title: 'Development Perspectives II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 2 Semester 1
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 216'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 216',
    title: 'Intermediate Microeconomics',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 218'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 218',
    title: 'Quantitative Methods I',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 220'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 220',
    title: 'Development Economics',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 2 Semester 2
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 217'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 217',
    title: 'Intermediate Macroeconomics',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 219'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 219',
    title: 'Quantitative Methods II',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'AS 299'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'AS 299',
    title: 'Second-Year Practical Training',
    credits: 8,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 3 Semester 1
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 366'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 366',
    title: 'Advanced Microeconomics',
    credits: 12,
    yearOfStudy: 3,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 374'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 374',
    title: 'Applied Econometrics',
    credits: 12,
    yearOfStudy: 3,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 382'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 382',
    title: 'Public Sector Economics',
    credits: 12,
    yearOfStudy: 3,
    semester: 1,
    status: 'Elective',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 3 Semester 2
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 367'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 367',
    title: 'Advanced Macroeconomics',
    credits: 12,
    yearOfStudy: 3,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 383'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 383',
    title: 'International Economics',
    credits: 12,
    yearOfStudy: 3,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'ba-economics', 'EC 399'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'ba-economics',
    code: 'EC 399',
    title: 'Research Project in Economics',
    credits: 12,
    yearOfStudy: 3,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
];

// C. BSc Computer Science Curriculum (CoICT Department of Computer Science & Engineering)
const AUDITED_BSC_CS_COURSES: CourseRecord[] = [
  // Year 1 Semester 1
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 174'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 174',
    title: 'Introduction to Artificial Intelligence',
    credits: 9,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 151'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 151',
    title: 'Computer Organization and Architecture',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'MT 100'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'bsc-cs',
    code: 'MT 100',
    title: 'Foundations of Analysis',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'DS 112'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'bsc-cs',
    code: 'DS 112',
    title: 'Development Perspectives I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 171'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 171',
    title: 'Introduction to Computer Programming',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 1 Semester 2
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 172'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 172',
    title: 'Data Structures and Algorithms',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 173'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 173',
    title: 'Object Oriented Programming in Java',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'MT 127'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'bsc-cs',
    code: 'MT 127',
    title: 'Linear Algebra I',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'DS 113'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'bsc-cs',
    code: 'DS 113',
    title: 'Development Perspectives II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 2 Semester 1
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 234'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 234',
    title: 'Object Oriented Analysis and Design',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 243'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 243',
    title: 'Database Management Systems',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 211'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 211',
    title: 'Operating Systems',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 2 Semester 2
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 253'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 253',
    title: 'Computer Networks',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 273'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 273',
    title: 'Web Technologies and Development',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 284'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 284',
    title: 'Software Engineering',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 299'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 299',
    title: 'Practical Training I',
    credits: 8,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 3 Semester 1
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 351'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 351',
    title: 'Distributed Systems',
    credits: 12,
    yearOfStudy: 3,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 362'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 362',
    title: 'Information Systems Security',
    credits: 12,
    yearOfStudy: 3,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 374'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 374',
    title: 'Machine Learning',
    credits: 12,
    yearOfStudy: 3,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 3 Semester 2
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 381'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 381',
    title: 'Mobile Application Development',
    credits: 12,
    yearOfStudy: 3,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 383'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 383',
    title: 'Cloud Computing',
    credits: 12,
    yearOfStudy: 3,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-cs', 'CS 399'),
    universityId: 'udsm',
    academicUnitId: 'coict',
    departmentId: 'dept-cse',
    programmeId: 'bsc-cs',
    code: 'CS 399',
    title: 'Final Year Project in Computer Science',
    credits: 12,
    yearOfStudy: 3,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
];

// D. Bachelor of Commerce in Accounting (UDBS Department of Accounting)
const AUDITED_BCOM_ACCOUNTING_COURSES: CourseRecord[] = [
  // Year 1 Semester 1
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'AC 100'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bcom-accounting',
    code: 'AC 100',
    title: 'Principles of Accounting I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'FN 100'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'bcom-accounting',
    code: 'FN 100',
    title: 'Principles of Microeconomics',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'MS 100'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bcom-accounting',
    code: 'MS 100',
    title: 'Quantitative Methods I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'IM 100'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-management',
    programmeId: 'bcom-accounting',
    code: 'IM 100',
    title: 'Introduction to Business',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'DS 112'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'bcom-accounting',
    code: 'DS 112',
    title: 'Development Perspectives I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 1 Semester 2
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'AC 101'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bcom-accounting',
    code: 'AC 101',
    title: 'Principles of Accounting II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'FN 101'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'bcom-accounting',
    code: 'FN 101',
    title: 'Principles of Macroeconomics',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'MS 101'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bcom-accounting',
    code: 'MS 101',
    title: 'Quantitative Methods II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'DS 113'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'bcom-accounting',
    code: 'DS 113',
    title: 'Development Perspectives II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 2 Semester 1
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'AC 200'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bcom-accounting',
    code: 'AC 200',
    title: 'Financial Accounting I',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'AC 202'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bcom-accounting',
    code: 'AC 202',
    title: 'Cost Accounting',
    credits: 12,
    yearOfStudy: 2,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 2 Semester 2
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'AC 201'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bcom-accounting',
    code: 'AC 201',
    title: 'Financial Accounting II',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'AC 203'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bcom-accounting',
    code: 'AC 203',
    title: 'Management Accounting',
    credits: 12,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bcom-accounting', 'AC 299'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bcom-accounting',
    code: 'AC 299',
    title: 'Practical Training in Accounting',
    credits: 8,
    yearOfStudy: 2,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
];

// E. Bachelor of Laws (UDSoL Department of Private Law)
const AUDITED_LLB_COURSES: CourseRecord[] = [
  // Year 1 Semester 1
  {
    id: buildStableCourseId('udsm', 'llb', 'LW 100'),
    universityId: 'udsm',
    academicUnitId: 'udsol',
    departmentId: 'dept-private-law',
    programmeId: 'llb',
    code: 'LW 100',
    title: 'Constitutional Law I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'llb', 'LW 102'),
    universityId: 'udsm',
    academicUnitId: 'udsol',
    departmentId: 'dept-private-law',
    programmeId: 'llb',
    code: 'LW 102',
    title: 'Law of Contract I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'llb', 'LW 104'),
    universityId: 'udsm',
    academicUnitId: 'udsol',
    departmentId: 'dept-private-law',
    programmeId: 'llb',
    code: 'LW 104',
    title: 'Criminal Law and Procedure I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'llb', 'LW 106'),
    universityId: 'udsm',
    academicUnitId: 'udsol',
    departmentId: 'dept-private-law',
    programmeId: 'llb',
    code: 'LW 106',
    title: 'Legal Method I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'llb', 'DS 112'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'llb',
    code: 'DS 112',
    title: 'Development Perspectives I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },

  // Year 1 Semester 2
  {
    id: buildStableCourseId('udsm', 'llb', 'LW 101'),
    universityId: 'udsm',
    academicUnitId: 'udsol',
    departmentId: 'dept-private-law',
    programmeId: 'llb',
    code: 'LW 101',
    title: 'Constitutional Law II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'llb', 'LW 103'),
    universityId: 'udsm',
    academicUnitId: 'udsol',
    departmentId: 'dept-private-law',
    programmeId: 'llb',
    code: 'LW 103',
    title: 'Law of Contract II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'llb', 'LW 105'),
    universityId: 'udsm',
    academicUnitId: 'udsol',
    departmentId: 'dept-private-law',
    programmeId: 'llb',
    code: 'LW 105',
    title: 'Criminal Law and Procedure II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'llb', 'LW 107'),
    universityId: 'udsm',
    academicUnitId: 'udsol',
    departmentId: 'dept-private-law',
    programmeId: 'llb',
    code: 'LW 107',
    title: 'Legal Method II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'llb', 'DS 113'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'llb',
    code: 'DS 113',
    title: 'Development Perspectives II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
];

// F. BSc Actuarial Sciences (CoNAS Department of Mathematics)
const AUDITED_BSC_ACTUARIAL_COURSES: CourseRecord[] = [
  {
    id: buildStableCourseId('udsm', 'bsc-actuarial', 'MT 100'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'bsc-actuarial',
    code: 'MT 100',
    title: 'Foundations of Analysis',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-actuarial', 'MT 127'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'bsc-actuarial',
    code: 'MT 127',
    title: 'Linear Algebra I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-actuarial', 'ST 113'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'bsc-actuarial',
    code: 'ST 113',
    title: 'Basic Statistics',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-actuarial', 'FN 100'),
    universityId: 'udsm',
    academicUnitId: 'udse',
    departmentId: 'dept-economics',
    programmeId: 'bsc-actuarial',
    code: 'FN 100',
    title: 'Principles of Microeconomics',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-actuarial', 'DS 112'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'bsc-actuarial',
    code: 'DS 112',
    title: 'Development Perspectives I',
    credits: 12,
    yearOfStudy: 1,
    semester: 1,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-actuarial', 'MT 114'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-math',
    programmeId: 'bsc-actuarial',
    code: 'MT 114',
    title: 'Advanced Calculus',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-actuarial', 'ST 114'),
    universityId: 'udsm',
    academicUnitId: 'conas',
    departmentId: 'dept-stats',
    programmeId: 'bsc-actuarial',
    code: 'ST 114',
    title: 'Probability and Distribution Theory II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-actuarial', 'AC 100'),
    universityId: 'udsm',
    academicUnitId: 'udbs',
    departmentId: 'dept-accounting',
    programmeId: 'bsc-actuarial',
    code: 'AC 100',
    title: 'Principles of Accounting I',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
  {
    id: buildStableCourseId('udsm', 'bsc-actuarial', 'DS 113'),
    universityId: 'udsm',
    academicUnitId: 'ids',
    departmentId: 'dept-dev-studies',
    programmeId: 'bsc-actuarial',
    code: 'DS 113',
    title: 'Development Perspectives II',
    credits: 12,
    yearOfStudy: 1,
    semester: 2,
    status: 'Core',
    academicYear: '2025/2026',
    verified: true,
    source: OFFICIAL_PROSPECTUS_CITATION,
  },
];

// Complete combined verified course catalogue
export const AUDITED_UDSM_COURSES: CourseRecord[] = [
  ...AUDITED_BSC_MATH_STATS_COURSES,
  ...AUDITED_BA_ECONOMICS_COURSES,
  ...AUDITED_BSC_CS_COURSES,
  ...AUDITED_BCOM_ACCOUNTING_COURSES,
  ...AUDITED_LLB_COURSES,
  ...AUDITED_BSC_ACTUARIAL_COURSES,
];

// ---------------------------------------------------------------------------
// AUDIT & VALIDATION ENGINE
// ---------------------------------------------------------------------------
export class UdsmCatalogueAuditService {
  /**
   * Performs an audit of an input catalogue against the official UDSM Undergraduate Prospectus 2025/2026
   */
  public auditCatalogue(input: {
    existingUnits: AcademicUnitRecord[];
    existingDepts: DepartmentRecord[];
    existingProgs: ProgrammeRecord[];
    existingCourses: CourseRecord[];
  }): CatalogueAuditReport {
    const unitsAdded: string[] = [];
    const unitsCorrected: string[] = [];
    const departmentsAdded: string[] = [];
    const departmentsMovedOrCorrected: string[] = [];
    const programmesAdded: string[] = [];
    const programmesCorrected: string[] = [];
    const coursesAdded: string[] = [];
    const coursesCorrected: string[] = [];
    const duplicatesRemoved: string[] = [];
    const unverifiedRecords: string[] = [];

    // Track hierarchy anomalies detected
    let missingAcademicUnitsDetected = 0;
    let wrongUnitTypesDetected = 0;
    let departmentsUnderWrongUnitsDetected = 0;
    let missingDepartmentsDetected = 0;
    let programmesUnderWrongDepartmentsDetected = 0;
    let missingProgrammesDetected = 0;
    let coursesUnderWrongProgrammesDetected = 0;
    let duplicateCoursesDetected = 0;
    let invalidYearSemesterDetected = 0;

    // 1. Audit Academic Units
    const existingUnitMap = new Map<string, AcademicUnitRecord>();
    input.existingUnits.forEach((u) => existingUnitMap.set(u.id, u));

    for (const officialUnit of AUDITED_UDSM_ACADEMIC_UNITS) {
      const existing = existingUnitMap.get(officialUnit.id);
      if (!existing) {
        missingAcademicUnitsDetected++;
        unitsAdded.push(`Added missing academic unit: ${officialUnit.shortName} (${officialUnit.name}) [${officialUnit.type}]`);
      } else {
        if (existing.type !== officialUnit.type) {
          wrongUnitTypesDetected++;
          unitsCorrected.push(`Corrected unit type for ${existing.id}: "${existing.type}" -> "${officialUnit.type}"`);
        }
      }
    }

    // 2. Audit Departments
    const existingDeptMap = new Map<string, DepartmentRecord>();
    input.existingDepts.forEach((d) => existingDeptMap.set(d.id, d));

    for (const officialDept of AUDITED_UDSM_DEPARTMENTS) {
      const existing = existingDeptMap.get(officialDept.id);
      if (!existing) {
        missingDepartmentsDetected++;
        departmentsAdded.push(`Added missing department: ${officialDept.name} under unit ${officialDept.academicUnitId}`);
      } else {
        if (existing.academicUnitId !== officialDept.academicUnitId) {
          departmentsUnderWrongUnitsDetected++;
          departmentsMovedOrCorrected.push(
            `Moved department "${existing.name}" from wrong unit "${existing.academicUnitId}" to official unit "${officialDept.academicUnitId}"`
          );
        }
      }
    }

    // 3. Audit Programmes
    const existingProgMap = new Map<string, ProgrammeRecord>();
    input.existingProgs.forEach((p) => existingProgMap.set(p.id, p));

    for (const officialProg of AUDITED_UDSM_PROGRAMMES) {
      const existing = existingProgMap.get(officialProg.id);
      if (!existing) {
        missingProgrammesDetected++;
        programmesAdded.push(`Added missing programme: ${officialProg.name} (${officialProg.shortName})`);
      } else {
        let corrected = false;
        if (existing.academicUnitId !== officialProg.academicUnitId) {
          programmesUnderWrongDepartmentsDetected++;
          programmesCorrected.push(
            `Corrected programme "${existing.name}" unit: from "${existing.academicUnitId}" to "${officialProg.academicUnitId}"`
          );
          corrected = true;
        }
        if (existing.departmentId !== officialProg.departmentId) {
          programmesCorrected.push(
            `Corrected programme "${existing.name}" department: from "${existing.departmentId}" to "${officialProg.departmentId}"`
          );
          corrected = true;
        }
      }
    }

    // 4. Audit Courses & Deduplication
    const seenCourseKeys = new Set<string>();
    const existingCourseMap = new Map<string, CourseRecord>();
    input.existingCourses.forEach((c) => {
      const key = `${c.programmeId}_${c.yearOfStudy}_${c.semester}_${normalizeCourseCode(c.code)}`;
      if (seenCourseKeys.has(key)) {
        duplicateCoursesDetected++;
        duplicatesRemoved.push(`Identified duplicate course: ${c.code} in programme ${c.programmeId}`);
      } else {
        seenCourseKeys.add(key);
        existingCourseMap.set(c.id, c);
      }
    });

    for (const officialCourse of AUDITED_UDSM_COURSES) {
      const existing = existingCourseMap.get(officialCourse.id);
      if (!existing) {
        coursesAdded.push(`Added missing course: ${officialCourse.code} (${officialCourse.title}) in ${officialCourse.programmeId}`);
      } else {
        const issues: string[] = [];
        if (existing.credits !== officialCourse.credits) {
          issues.push(`credits ${existing.credits} -> ${officialCourse.credits}`);
        }
        if (existing.status !== officialCourse.status) {
          issues.push(`status ${existing.status} -> ${officialCourse.status}`);
        }
        if (existing.academicUnitId !== officialCourse.academicUnitId) {
          coursesUnderWrongProgrammesDetected++;
          issues.push(`unit ${existing.academicUnitId} -> ${officialCourse.academicUnitId}`);
        }
        if (existing.departmentId !== officialCourse.departmentId) {
          issues.push(`department ${existing.departmentId} -> ${officialCourse.departmentId}`);
        }
        if (issues.length > 0) {
          coursesCorrected.push(`Corrected ${officialCourse.code} (${issues.join(', ')})`);
        }
      }
    }

    const report: CatalogueAuditReport = {
      timestamp: new Date().toISOString(),
      source: OFFICIAL_PROSPECTUS_CITATION,
      summary: {
        academicUnitsFound: AUDITED_UDSM_ACADEMIC_UNITS.length,
        departmentsFound: AUDITED_UDSM_DEPARTMENTS.length,
        programmesFound: AUDITED_UDSM_PROGRAMMES.length,
        coursesFound: AUDITED_UDSM_COURSES.length,
        recordsAdded: unitsAdded.length + departmentsAdded.length + programmesAdded.length + coursesAdded.length,
        recordsCorrected:
          unitsCorrected.length +
          departmentsMovedOrCorrected.length +
          programmesCorrected.length +
          coursesCorrected.length,
        recordsRemovedAsDuplicatesOrInvalid: duplicatesRemoved.length,
        unverifiedRecordsCount: unverifiedRecords.length,
      },
      details: {
        unitsAdded,
        unitsCorrected,
        departmentsAdded,
        departmentsMovedOrCorrected,
        programmesAdded,
        programmesCorrected,
        coursesAdded,
        coursesCorrected,
        duplicatesRemoved,
        unverifiedRecords,
      },
      hierarchyCheck: {
        missingAcademicUnitsDetected,
        wrongUnitTypesDetected,
        departmentsUnderWrongUnitsDetected,
        missingDepartmentsDetected,
        programmesUnderWrongDepartmentsDetected,
        missingProgrammesDetected,
        coursesUnderWrongProgrammesDetected,
        duplicateCoursesDetected,
        invalidYearSemesterDetected,
      },
    };

    return report;
  }
}

export const udsmCatalogueAuditService = new UdsmCatalogueAuditService();
